# Generated by Django 5.2.9 on 2025-12-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeQueVaEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('audio_clip', models.FileField(blank=True, null=True, upload_to='de_que_va/clips/')),
                ('full_episode_url', models.URLField(blank=True, verbose_name='Link al episodi complet')),
                ('date', models.DateField()),
                ('episode_number', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'De Que Va Episode',
                'verbose_name_plural': 'De Que Va Episodes',
                'db_table': 'de_que_va_episodes',
                'ordering': ['-date'],
            },
        ),
    ]
