# Generated by Django 5.2.9 on 2026-03-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_habit_habitcompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='dequevaepisode',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
