# Generated by Django 5.2.14 on 2026-05-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_taskgroup_task_taskreschedule"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["scheduled_date", "order", "title"]},
        ),
        migrations.AddField(
            model_name="task",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
