# Generated by Django 5.2.9 on 2026-05-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_seed_default_task_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='granularity',
            field=models.CharField(choices=[('day', 'Dia'), ('week', 'Setmana'), ('month', 'Mes')], default='day', max_length=10),
        ),
    ]
