from .home import cv, home, narratives
from .tasks import (
    task_list,
    task_create,
    task_edit,
    task_complete,
    task_discard,
    task_cleanup,
    task_stats,
    task_group_list,
    task_group_edit,
    task_group_delete,
)
from .blog import (
    blog_detail,
    blog_editor,
    blog_list,
    blog_list_drafts,
    blog_save,
)
from .auth import login_view, logout_view
from .dashboard import (
    dashboard,
    episode_create,
    episode_delete,
    episode_edit,
    episode_list,
    habit_create,
    habit_day,
    habit_edit,
    habit_list,
)
from .projects import (
    project_de_que_va,
    project_doskvol_newspapers,
    project_jacobs_habits,
    project_ortografia,
    project_pomesagres,
    project_pomesagres_normes,
    projects_index,
)

__all__ = [
    "home",
    "cv",
    "narratives",
    "blog_list",
    "blog_detail",
    "blog_editor",
    "blog_save",
    "blog_list_drafts",
    "login_view",
    "logout_view",
    "dashboard",
    "episode_list",
    "episode_create",
    "episode_edit",
    "episode_delete",
    "habit_list",
    "habit_create",
    "habit_day",
    "habit_edit",
    "projects_index",
    "project_de_que_va",
    "project_doskvol_newspapers",
    "project_ortografia",
    "project_pomesagres",
    "project_pomesagres_normes",
    "project_jacobs_habits",
    "task_list",
    "task_create",
    "task_edit",
    "task_complete",
    "task_discard",
    "task_cleanup",
    "task_stats",
    "task_group_list",
    "task_group_edit",
    "task_group_delete",
]
